spring:
  queue:
    name: response.queue
  rabbitmq:
    notification:
      port: 5672
      host: 172.25.1.82
      virtual: market
      username: admin
      password: admin
      autoCreate: false
      exchange:
        email: exchange.market
        sms: exchange.market.Lookup
      routingKey:
        email: market.routingkey
        sms: market_lookup.routingkey
    exchange:
      name: response.exchange
    routingKey:
      name: response.routingkey
    port: 5672
    host: 172.25.1.82
    username: admin
    password: admin
    virtual: n
    market:
      port: 5672
      host: 172.25.1.82
      virtual: market
      username: admin
      password: admin
      plate:
        exchange: plateExchange
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
  application:
    locale: en-us
    name: admin
  datasource:
    url: jdbc:postgresql://172.25.1.82:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      #maximum-pool-size: 5
      data-source-properties:
        pool-name: ernyka
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
##  data:
##    mongodb:
##      uri: mongodb://172.25.1.82:27017/bitrade
##      database: bitrade
##    jpa:
##      repositories:
##        enabled: true
#  redis:
##    host: localhost
##    port: 6379
#    pool:
#      max-active: 300
#      max-wait: 60000
#      max-idle: 100
#      min-idle: 20
##    timeout: 30000
##    password:
#  jackson:
#    serialization:
#      indent_output: true
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+3:30
#  session:
#    store-type: none
#  kafka:
#    bootstrapservers: localhost:9092
#
#    producer:
#      retries: 0
#      batch:
#        size: 256
#      linger: 1
#      buffer:
#        memory: 1048576
#    consumer:
#      enable:
#        auto:
#          commit: false
#      session:
#        timeout: 15000
#      auto:
#        commit:
#          interval: 100
#        offset:
#          reset: earliest
#      group:
#        id: default-group
#      concurrency: 9
#      maxPollRecordsConfig: 50
#  devtools:
#    restart:
#      enabled: true
#  freemarker:
#    cache: false
#    template-loader-path: classpath:/templates
##  mail:
##    host: smtp.126.com
##    port: 465
##    properties:
##      mail:
##        smtp:
##          socketFactory:
##            class: javax.net.ssl.SSLSocketFactory
##          auth: true
##          starttls:
##            enable: true
##            required: true
##    username: 21322aaa@126.com
##    password: dssasdd3211
##eureka:
##  client:
##    serviceUrl:
##      defaultZone: http://127.0.0.1:7000/eureka/
##  instance:
##    prefer-ip-address: true